"""add Holdings model, wire GoalFunding.holding_id FK (D-013, D-044)

Revision ID: a6cd8d30a707
Revises: 069bc85fc512
Create Date: 2026-08-03 21:44:44.204454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a6cd8d30a707'
down_revision: Union[str, None] = '069bc85fc512'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('holdings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('product_type', sa.String(), nullable=False),
    sa.Column('alias', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('characteristics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'alias', name='uq_holdings_user_alias')
    )
    op.create_index(op.f('ix_holdings_product_type'), 'holdings', ['product_type'], unique=False)
    op.create_index(op.f('ix_holdings_user_id'), 'holdings', ['user_id'], unique=False)
    op.create_foreign_key(
        'fk_goal_fundings_holding_id_holdings', 'goal_fundings', 'holdings', ['holding_id'], ['id'], ondelete='CASCADE'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_goal_fundings_holding_id_holdings', 'goal_fundings', type_='foreignkey')
    op.drop_index(op.f('ix_holdings_user_id'), table_name='holdings')
    op.drop_index(op.f('ix_holdings_product_type'), table_name='holdings')
    op.drop_table('holdings')
    # ### end Alembic commands ###
