"""add discretionary_categories table (BQ-010, D-038)

Revision ID: ce8262c241ff
Revises: a6cd8d30a707
Create Date: 2026-08-03 22:29:09.740052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce8262c241ff'
down_revision: Union[str, None] = 'a6cd8d30a707'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discretionary_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('planned_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discretionary_categories_user_id'), 'discretionary_categories', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_discretionary_categories_user_id'), table_name='discretionary_categories')
    op.drop_table('discretionary_categories')
    # ### end Alembic commands ###
