import { useRef, useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { ChatThread, type ChatThreadHandle } from '../components/ChatThread';
import { colors, font, radius, spacing } from '../design/tokens';

// D-058: chip-guided conversation (Option C — no structured field anywhere), the default
// landing screen right after registration, never a hard gate. "Skip for now" is always
// visible; once a chip or typed message has been sent, the same button becomes "Done —
// go to app" (still just dismisses). Resuming later is the persistent Chat tab (BQ-024) —
// no separate resume UI, per D-058's own "left to build-time, low-stakes" note.
// `track`: BQ-042/D-084 — each chip names its onboarding track with certainty, passed as a
// deterministic hint (app/lib/chat.ts's OnboardingRequest) so the backend only classifies
// free-typed messages.
const CHIP_STARTERS = [
  {
    label: 'I just started earning',
    message: "I just started earning and I'm not sure where to begin.",
    track: 'fresh_starter',
  },
  {
    label: 'I have a loan/EMI',
    message: 'I have a loan or EMI and want to understand it better.',
    track: 'reactive_dabbler',
  },
  {
    label: 'I already track my budget',
    message: 'I already track my budget and want to go deeper.',
    track: 'habit_former',
  },
  {
    label: 'Something else',
    message: "I'm not sure yet — help me figure out where to start.",
    track: 'unclassified',
  },
];

export function OnboardingScreen({ userId, onDone }: { userId: string; onDone: () => void }) {
  const threadRef = useRef<ChatThreadHandle>(null);
  const [engaged, setEngaged] = useState(false);

  return (
    <View style={styles.container}>
      <View style={styles.header}>
        <Text style={styles.title}>Welcome to FinTutor</Text>
        {/* P9/D-058: must render unconditionally, from the very first frame — never
            gated behind `engaged` or any other state. Only the label text changes. */}
        <Pressable onPress={onDone} hitSlop={8}>
          <Text style={styles.skip}>{engaged ? 'Done — go to app' : 'Skip for now'}</Text>
        </Pressable>
      </View>

      <ChatThread
        ref={threadRef}
        userId={userId}
        onboarding
        onMessageSent={() => setEngaged(true)}
        emptyState={
          <View style={styles.emptyState}>
            <Text style={styles.prompt}>What brings you here today?</Text>
            <View style={styles.chipRow}>
              {CHIP_STARTERS.map((chip) => (
                <Pressable
                  key={chip.label}
                  style={styles.chip}
                  onPress={() => threadRef.current?.send(chip.message, undefined, chip.track)}
                >
                  <Text style={styles.chipText}>{chip.label}</Text>
                </Pressable>
              ))}
            </View>
          </View>
        }
      />
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.screen },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: spacing.xl,
    paddingTop: spacing.xxl,
    paddingBottom: spacing.md,
  },
  title: { fontSize: 20, fontWeight: '600', color: colors.ink, fontFamily: font.ui },
  skip: { color: colors.inkSecondary, fontSize: 14, fontFamily: font.ui },
  emptyState: { alignItems: 'center' },
  // Static product copy, font.ui — and correctly so under P11. The distinction P11 draws
  // is about the act of EXPLAINING (font.tutor), not about whether the copy happened to be
  // written by a person or generated by the model. This string is a prompt asking the user
  // a question, not an explanation of anything, so font.ui is right regardless of
  // provenance — same reasoning that puts static teaching copy elsewhere in font.tutor.
  prompt: {
    fontSize: 16,
    color: colors.ink,
    fontFamily: font.ui,
    marginBottom: spacing.lg,
    textAlign: 'center',
  },
  chipRow: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'center', gap: spacing.sm },
  chip: {
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.line,
    borderRadius: radius.pill,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
  },
  chipText: { fontSize: 14, color: colors.ink, fontFamily: font.ui },
});
